{
 "title": "Dashboard dominios",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Group", "label": "Group", "query": "*" },
   { "name": "Domain", "query": "$Group.*" }
  ]
 },
 "panels": [
  {
   "title": "Informacoes detalhadas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "/.*/" },
       "group": { "filter": "$Group" },
       "host": { "filter": "$Domain" },
       "item": { "filter": "Status" },
       "mode": 2,
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Localizacao",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "/.*/" },
       "group": { "filter": "$Group" },
       "host": { "filter": "$Domain" },
       "item": { "filter": "Localizacao" },
       "mode": 2,
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Dias para expirar o dominio",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "/.*/" },
       "group": { "filter": "$Group" },
       "host": { "filter": "$Domain" },
       "item": { "filter": "Dias para expirar o dominio" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Dias para expirar o dominio",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "/.*/" },
       "group": { "filter": "$Group" },
       "host": { "filter": "$Domain" },
       "item": { "filter": "Expiração do dominio" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Informacoes global de expiração.",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Dias Expiração dos dominios",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 2 },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "Dias para expirar o dominio" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Data Expiração dos dominios",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 2 },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "Expiração do dominio" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Dias para  Expiração o certificado digital",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "Dias para expirar o certificado digital"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}